version: '3'
services:
  server:
    build:
      context: .
      args:
        NPM_LOG_LEVEL: notice
    ports:
      - '${SERVER_PORT}:3000'
    environment:
      POSTGRESQL_URL: postgres://admin:admin@localhost:5432
      BCRYPT_SALT: 10
      POSTGRES_HOST_AUTH_METHOD: trust
      JWT_SECRET_KEY: '${JWT_SECRET_KEY}'
      JWT_EXPIRATION: '${JWT_EXPIRATION}'
    depends_on:
      - migrate
  migrate:
    build:
      context: .
      args:
        NPM_LOG_LEVEL: notice
    command: npm run db:init
    working_dir: /app/server
    environment:
      POSTGRESQL_URL: postgres://admin:admin@localhost:5432
      BCRYPT_SALT: 10
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      ports: ${POSTGRESQL_PORT}:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          'CMD',
          'pg_isready',
          '-q',
          '-d',
          '${POSTGRESQL_DB_NAME}',
          '-U',
          '${POSTGRESQL_USER}',
        ]
      timeout: 45s
      interval: 10s
      retries: 10
volumes:
  postgres: ~
