version: '3'
services:
  db:
    image: postgres:12
    ports:
      - '${POSTGRESQL_PORT}:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~
