/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsOptional,
  ValidateNested,
  IsNumber,
} from "class-validator";
import { EventOrganizerWhereUniqueInput } from "../../eventOrganizer/base/EventOrganizerWhereUniqueInput";
import { Type } from "class-transformer";
import { SponsorUpdateManyWithoutEventsInput } from "./SponsorUpdateManyWithoutEventsInput";
import { TicketUpdateManyWithoutEventsInput } from "./TicketUpdateManyWithoutEventsInput";
@InputType()
class EventUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: () => EventOrganizerWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => EventOrganizerWhereUniqueInput)
  @IsOptional()
  @Field(() => EventOrganizerWhereUniqueInput, {
    nullable: true,
  })
  eventOrganizer?: EventOrganizerWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  images?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  price?: number | null;

  @ApiProperty({
    required: false,
    type: () => SponsorUpdateManyWithoutEventsInput,
  })
  @ValidateNested()
  @Type(() => SponsorUpdateManyWithoutEventsInput)
  @IsOptional()
  @Field(() => SponsorUpdateManyWithoutEventsInput, {
    nullable: true,
  })
  tagd?: SponsorUpdateManyWithoutEventsInput;

  @ApiProperty({
    required: false,
    type: () => TicketUpdateManyWithoutEventsInput,
  })
  @ValidateNested()
  @Type(() => TicketUpdateManyWithoutEventsInput)
  @IsOptional()
  @Field(() => TicketUpdateManyWithoutEventsInput, {
    nullable: true,
  })
  tickets?: TicketUpdateManyWithoutEventsInput;
}
export { EventUpdateInput };
