/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested } from "class-validator";
import { EventUpdateManyWithoutEventOrganizersInput } from "./EventUpdateManyWithoutEventOrganizersInput";
import { Type } from "class-transformer";
import { TicketUpdateManyWithoutEventOrganizersInput } from "./TicketUpdateManyWithoutEventOrganizersInput";
@InputType()
class EventOrganizerUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: () => EventUpdateManyWithoutEventOrganizersInput,
  })
  @ValidateNested()
  @Type(() => EventUpdateManyWithoutEventOrganizersInput)
  @IsOptional()
  @Field(() => EventUpdateManyWithoutEventOrganizersInput, {
    nullable: true,
  })
  events?: EventUpdateManyWithoutEventOrganizersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  payments?: string | null;

  @ApiProperty({
    required: false,
    type: () => TicketUpdateManyWithoutEventOrganizersInput,
  })
  @ValidateNested()
  @Type(() => TicketUpdateManyWithoutEventOrganizersInput)
  @IsOptional()
  @Field(() => TicketUpdateManyWithoutEventOrganizersInput, {
    nullable: true,
  })
  tickets?: TicketUpdateManyWithoutEventOrganizersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string | null;
}
export { EventOrganizerUpdateInput };
