/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateSponsorArgs } from "./CreateSponsorArgs";
import { UpdateSponsorArgs } from "./UpdateSponsorArgs";
import { DeleteSponsorArgs } from "./DeleteSponsorArgs";
import { SponsorFindManyArgs } from "./SponsorFindManyArgs";
import { SponsorFindUniqueArgs } from "./SponsorFindUniqueArgs";
import { Sponsor } from "./Sponsor";
import { Event } from "../../event/base/Event";
import { SponsorService } from "../sponsor.service";

@graphql.Resolver(() => Sponsor)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class SponsorResolverBase {
  constructor(
    protected readonly service: SponsorService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Sponsor",
    action: "read",
    possession: "any",
  })
  async _sponsorsMeta(
    @graphql.Args() args: SponsorFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Sponsor])
  @nestAccessControl.UseRoles({
    resource: "Sponsor",
    action: "read",
    possession: "any",
  })
  async sponsors(
    @graphql.Args() args: SponsorFindManyArgs
  ): Promise<Sponsor[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Sponsor, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Sponsor",
    action: "read",
    possession: "own",
  })
  async sponsor(
    @graphql.Args() args: SponsorFindUniqueArgs
  ): Promise<Sponsor | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Sponsor)
  @nestAccessControl.UseRoles({
    resource: "Sponsor",
    action: "create",
    possession: "any",
  })
  async createSponsor(
    @graphql.Args() args: CreateSponsorArgs
  ): Promise<Sponsor> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        event: args.data.event
          ? {
              connect: args.data.event,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Sponsor)
  @nestAccessControl.UseRoles({
    resource: "Sponsor",
    action: "update",
    possession: "any",
  })
  async updateSponsor(
    @graphql.Args() args: UpdateSponsorArgs
  ): Promise<Sponsor | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          event: args.data.event
            ? {
                connect: args.data.event,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Sponsor)
  @nestAccessControl.UseRoles({
    resource: "Sponsor",
    action: "delete",
    possession: "any",
  })
  async deleteSponsor(
    @graphql.Args() args: DeleteSponsorArgs
  ): Promise<Sponsor | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Event, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Event",
    action: "read",
    possession: "any",
  })
  async event(@graphql.Parent() parent: Sponsor): Promise<Event | null> {
    const result = await this.service.getEvent(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
